<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function sortByDate()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select("p")->from("AppBundle:Post", "p")->orderBy('p.created', 'DESC');

        return $query->getQuery()->getResult();
    }
}
